export { IResult } from './result';
export { IAssertion } from './assertion';
export { equality } from './equality';
export { approximately } from './approximately';
export { noReturn } from './no-return';
export { permutation } from './permutation';
export { unmodified } from './unmodified';
// export { createGrayscaleBitmapAssertion, createRgbBitmapAssertion } from './bitmap';
export { returnValue } from './return-value';
export { parameter } from './parameter';
export { decorate } from './decorator';
export { sequence } from './sequence';